server:
  port: 9999  
spring:
  jpa:
    open-in-view: false
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans : true
#        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/DBTestTrimix 
    username: database_trimix
    password: 123